### ISSUE TITLE
Get Ip Request Failure?

### ISSUE THREAD

**Issue by Insane-Agar** [AJS-development/Ogar-unlimited#1149]
Please read the FAQ in advance.

YOU MUST SEARCH UP YOUR ERROR FIRST TO SEE IF IT IS REPRODUCED

**What game mode were you in when you had the issue?**
Not Relevant to my issue
**What version are you on?**
Server Version 17.3.6, Statistics Version 1.1.2
What command did you type if any?
I did not type anything at that point.
**You must have a description as well**
I started my server this morning testing my custom client, I very soon realized no one was joining, and this was strange to me because my server usually has players joining almost immediately. I went to check if the stats.ogarul.tk was down, but it was up and working fine. After about 30 minutes of looking for my problem I finally found it. It seems that the stats.ogarul.tk/getip link did not get the right ip. The ip that my friends used to join is the one from whatsmyip.org. I am very concerned, considering the getip link was getting the right ip yesterday and suddenly started getting a strange ip. I'm not sure if this is a problem with your servers, or my IP. The IP that it should be getting is 68.38.169.151, the IP it is getting is 108.162.238.136. Also my server does not appear in the Stats list when it gets the second IP.
**Most common questions involve:**

Why is there an error "Cannot find module"
A: Do npm install after you cd into the repo.

VIOLATORS OF THIS WILL BE BANNED FOR 1 MONTH

**Comment by XtremePlayzCODE** [comment]
Maybe using a vpn (tunnelbear, browsec, etc)

**Comment by fayizan** [comment]
I have the same problem but I fixed it..!!
Change the config `usevpsip = 0` and paste your correct vps ip in `Customip = `

![screenshot_2016-06-25-22-07-18](https://cloud.githubusercontent.com/assets/19163419/16357898/48302398-3b21-11e6-926c-06437ed8fec5.png)

**Comment by LegitSoulja** [comment]
If you are getting an ip, that is different, yes do what @fayizan did.

**Comment by Insane-Agar** [comment]
Thanks @fayizan worked, still not sure why it suddenly stopped working though. Well, thanks for your help

**Comment by LegitSoulja** [comment]
@Insane-Agar I'll fix it with a better solution.
