### ISSUE TITLE
Teleporting cells (Bug)

### ISSUE THREAD

**Issue by xMuratY** [AJS-development/Ogar-unlimited#733]
Servers have a map bug. teleporting players randomized and teleporting back location or gfx bug

**Comment by DarkZYT** [comment]
It happens sometimes , keep refreshing you page until it works correctly !

**Comment by ChefHunter** [comment]
The same issue happends to me. I don't think refreshing the page is a proper solution.

**Comment by ChefHunter** [comment]
From what I can tell, this should fix it
https://github.com/AJS-development/Ogar-unlimited/issues/734

**Comment by Andrews54757** [comment]
no, its because of the client

**Comment by ChefHunter** [comment]
It wasn't the client.
I don't think you understad what was happening.

**Comment by LegitSoulja** [comment]
@ChefHunter it's the client.. Not the server itself.

**Comment by ChefHunter** [comment]
I fixed my issue by fixing getNextId...

**Comment by LegitSoulja** [comment]
@ChefHunter I have already fixed that :/

**Comment by xMuratY** [comment]
I tested again now still have some bug all working good but why cant fix this bug and spectate button is dont working

my client http://agar.hotteam.tk

**Comment by firelightning13** [comment]
It's the client bug, even if you get rid of the error, sometimes you will still have it. (means it's not server's problem, happens to me too when im using my own client).

I think it's the packets problem? (from client)

**Comment by ChefHunter** [comment]
It's the server. I'm using the tomsterly client and it still bugs out.

**Comment by ChefHunter** [comment]
Can somone help
